# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2c9fb926b3a4793185bfaf2f42c5bde792979545da1a006d49b9349b6e834e0acb1c70198cb172496f6b117069f6421882c1d10db59a0ec100f6c0b92a2c9b8e

test:
  secret_key_base: 29800b3382ca04dcf2424c6b1c6cc4da135bafe5480a087b2e8a7609a33983595b9ca8571f240b36f757717fe5f135c73809bf9ee44094ed1c679cca515760ff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
